# alacrity

# import = ["~/.config/alacritty/dracula-pro-van-helsing.toml"]

import = ["~/.config/alacritty/dracula-pro.toml"]

[env]
TERM = "xterm-256color"

# [window]

# padding.x = 10

# padding.y = 10

# decorations = "Buttonless"

# opacity = 0.7

# blur = true

# option_as_alt = "Both"

[font]

# normal.family = "Dank Mono"

normal.family = "MonoLisa"

size = 18
